# Generated by Django 3.2.9 on 2022-01-14 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auctionlisting_auctionwinner_bid_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlisting',
            name='description',
            field=models.TextField(default='none'),
        ),
        migrations.AddField(
            model_name='auctionlisting',
            name='sold',
            field=models.BooleanField(default=False),
        ),
    ]
