# Generated by Django 3.2.9 on 2022-02-02 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_auto_20220123_1316'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bid',
            options={'ordering': ['date_added']},
        ),
    ]
